# Use the Apache Airflow 2.7.0 base image
FROM apache/airflow:2.7.0

# Switch to root user temporarily to perform package installation
USER root

# Install Python 3, pip3
RUN apt-get update && apt-get install -y python3 python3-pip

# Switch back to a non-root user
USER airflow

# Install python libraries
RUN pip3 install psycopg2-binary python-decouple sqlalchemy 

